<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="MAIN" Id="{9ad04803-898f-4588-9872-113a1d3cdead}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Nappi: BOOL;
	Vipu1: BOOL;
	Vipu2: BOOL;
	NappiOhje: INT;
	
	Numero: INT;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF General.ReadyForAction THEN //fiksumpi järjestely tälle pitäis olla
	
P_Safety();
P_CONTROL();		// Using buttons, handling sensors
P_WritePersistentData();	// Writes persistent variables to memory every 10 seconds
OVERVIEW_FBD();				// FBD View of all FB's. Useful visualization of whats happening
// P_Environment_Control -> Is a separate slow task, not to be called from MAIN
END_IF
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="139" Count="7" />
      <LineId Id="127" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>