<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="P_AUTOMATION" Id="{533f5014-8755-47f8-a5a5-ad530ab45145}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_AUTOMATION
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="P_AUTOMATION">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>