<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="P_Temperature_Obs" Id="{62b7f54b-59f2-4e90-8e41-9f44922b00b4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Temperature_Obs
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="P_Temperature_Obs">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>