<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="MAIN_KOLMI" Id="{48d5b021-12c4-493c-a120-e4027bfa7c90}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN_KOLMI
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN_KOLMI">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>