<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="GVL" Id="{eac86cfe-cb67-4d23-9bd9-0c199b371614}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM GVL
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="GVL">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>