<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="P_Safety" Id="{4a2af581-3054-4755-8b59-c878439b7ede}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Safety
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="P_Safety">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>