<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_GatoPerro" Id="{907c9889-847a-48a2-b378-14a1b7bf9287}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_GatoPerro
VAR_INPUT
END_VAR
VAR_OUTPUT
	Gato 		: BOOL;
	Perro 		: BOOL;
	GatoCount 	: INT;
	PerroCount 	: INT;

END_VAR
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[A_SensorHandling();

// Kierroslaskuri

// Magneettisensori näkee Gaton

// Valosensori näkee kumman vain

// Kumpi on kyseessä

]]></ST>
    </Implementation>
    <Action Name="A_SensorHandling" Id="{386bec3c-e6c8-43fa-a72f-e87306b77bbe}">
      <Implementation>
        <ST><![CDATA[

]]></ST>
      </Implementation>
    </Action>
    <Action Name="A_SignalLights" Id="{3702fc04-dc87-4f5a-8553-8d8da3b39a96}">
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Action>
    <LineIds Name="FB_GatoPerro">
      <LineId Id="61" Count="2" />
      <LineId Id="73" Count="0" />
      <LineId Id="65" Count="5" />
      <LineId Id="17" Count="0" />
    </LineIds>
    <LineIds Name="FB_GatoPerro.A_SensorHandling">
      <LineId Id="2" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_GatoPerro.A_SignalLights">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>