<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_Temperature" Id="{9a2b7f95-be9c-47c0-8be8-ac9885e66be5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Temperature
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Temperature">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>