<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="Controls_MAIN" Id="{27560784-429a-4cb9-b530-4b903427c533}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Controls_MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
//Aliohjelmiesn kutsuja läjä tänne
]]></ST>
    </Implementation>
    <LineIds Name="Controls_MAIN">
      <LineId Id="6" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>