<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="F_RotationsPerMinute" Id="{26c608cd-7a09-42cc-88c8-6cdabbc35695}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_RotationsPerMinute : UDINT
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//asd]]></ST>
    </Implementation>
    <LineIds Name="F_RotationsPerMinute">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>