<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="F_Sample" Id="{b265c7ce-0f94-49c5-94a9-8dcc1578d2ce}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Sample : INT
VAR_INPUT
	nVar1 : INT;
	nVar2 : INT;
	nVar3 : INT;
END_VAR
VAR
	FunTemp : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_Sample := nVar1 + nVar2 +nVar3;]]></ST>
    </Implementation>
    <LineIds Name="F_Sample">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>