<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_BlockPad" Id="{718ab21c-a86f-42b1-ad84-7eea86241524}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_BlockPad
VAR_INPUT
	iInput1 : BOOL;
	iInput2 : BOOL;
	iInput3 : BOOL;
	bDoorLock : BOOL;
END_VAR
VAR_OUTPUT
	
	Q : BOOL;
	oLight1 : BOOL;
	
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_BlockPad">
      <LineId Id="43" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>